Popup_title =              'Syaanh'
Login =                    '//div[@id="nav_lang_link"]//..//span[contains(text(), "Login")]'
Popup_login =              '//div[contains(text(), "Login")]'
Mobile_login =             '31003167'
Password_login =           '12345678'
Button_login =             '//div//button//span[contains(text(),"Login")]/..'
Service_cleaning =         'Cleaning & Home Maids'
Service =                  '//div[contains(text(),"Select a service")]'
Area =                     'Doha'
Requested_service =        'House maid'
Type =                     'Apartment'
Button_continue1 =          '//button[@class="btn create_page_continue top changeNextPage"]'
Button_continue2 =          '//button[@class="btn create_page_continue top changeNextPage active"]'
Button_continue3 =          '//button[@class="btn create_page_continue top changeNextPage active"][@data-key="2"]'
Button_continue4 =          '//button[@class="btn create_page_continue top changeNextPage active"][@data-key="3"]'
Button_final =              '//button[@id="final_page"]'
Button_confirm_and_send =   '//button[@id="create_page_save"]'
Nationality =               ' Any nationality'
Sex =                       'Female'
Required_materials =        'Client-owned'
Description_text =          'First order'
Preferred_time =            'Next week'
Step2 =                     'Select the location'
Step3 =                     'Choose nationality'
Step4 =                     'Describe your requirement clearly'
Step5 =                     'Add photos of the problem'
Popup_success =             '//span[@style="font-size: 32px;font-weight: bold"]'
Button_search =             '//*[@class="how-it-works-create-order"]/button'
list_categories =            '//div//div[contains(text(), "Choose category")]'
check_popup=                   '//*[@id="choose_service_category_all"]/div/div'


