Popup_title =              'Syaanh'
Login =                    '//div[@id="nav_lang_link"]//..//span[contains(text(), "Login")]'
Popup_login =              '//div[contains(text(), "Login")]'
Mobile_login =             '31003167'
Password_login =           '12345678'
Button_login =              '//div//button//span[contains(text(),"Login")]/..'
Mobile_login_invalid =             '1003167'
Password_login_invalid =           '12345678'
msg_login_invalid = '//span//strong[contains(text(),"Please enter valid email ID")]'