Login =                    '//div[@id="nav_lang_link"]//..//span[contains(text(), "Login")]'
Popup_login =              '//div[contains(text(), "Login")]'
Button_login =             '//div//button//span[contains(text(),"Login")]/..'
input_mobile =             '//input[@id="mobile_or_email"]'
input_password =           '//input[@id="login_password"]'
home_logo =                 '//div//a[@class="syaanh-logo"]'
home_title =                '//div//a[@class="home-link"]'
home_link_login =           '//div/../span[contains(text(),"Login")]'
home_search =               '//div//input[@placeholder="What needs to be done?"]'
home_categories =           '//div//a[@id="navbarDropdownMenuLink1"]'
home_language =             '//div[@class="for_language "]//a[@id="for_lang_drop"]'
home_btn_CrateOrder =       '//div[@class="topnav-right  topnav-right-guest  "]/button/span[contains(text(),"Create order")]'
home_txt_ShopCategories=    '//div//h3[contains(text(),"Shop categories")]'
home_link_seeMore =         '//div[@class="shop-categories_row shop-categories_row-one"]//a[contains(text(),"see more")]'
home_link_SelectService =          '//div[@class="home-services"]//div[contains(text(),"Select a service")]'