Login =                    '//*[@class="nav-link-login"]'
Popup_login =              '//div[contains(text(), "Login")]'
Button_login =             '//div//button//span[contains(text(),"Login")]/..'
langauage = '//a[@id="for_lang_drop"]'
Button_categories = '//*[@id="navbarDropdownMenuLink1"]'
icon_Syaanh = '//*[@class="syaanh-logo"]'
Button_create = '//*[@class="btn user-profile-create-order-button"]'
Shop_categories ='//*[@id="main_content"]//*[text()="Shop categories"]'