usr_btn_user_option =           "//div//a[@id='user_options']"
usr_btn_my_profile =            "//div[@class='dropdown-menu user-options show']//a[@href='https://dev.syaanh.com/en/profile']"
usr_txt_user_name =             "//div[@class='profile-username']//h1"
usr_btn_edit_name =             "//div[@class='profile-edit-pencil']//a[@class='btn']"
usr_popup_update_name =         "//div[@class='modal-content']//div[@class='modal-body']//div[@class='profile-update-header']"
usr_input_name =                "//input[@id='profile_update_name']"
usr_btn_update =                "//div//submit//span[contains(text(),'Update')]"
usr_txt_new_user_name =         "//div[@class='profile-username']//h1[contains(text(),'xxxx')]"
usr_txt_change_password =        "//div[@class='form-group']//span[contains(text(),'Change password')]"
usr_popup_change_password =     "//div[@class='modal-content']//div[@class='profile-update-header'][contains(text(),'Change password')]"
usr_input_new_password =        "//div//input[@id='profile_new_password']"
usr_input_confirm_password =    "//div//input[@id='password_confirm']"
usr_btn_update_password =       "//div//a[@class='btn-continue update-password-submit']//span[contains(text(),'Update')]"
usr_popup_password_updated =     "//div//span[contains(text(),'Password updated successfully!')]"