# This is a basic workflow to help you get started with Actions

name: Nightly workflow

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  schedule:
   - cron: "0 3 * * 1-5"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Prepare reports folder
        run: mkdir Reports

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          sudo pip3 install \
            robotframework==3.2.2 \
            robotframework-seleniumlibrary==4.5.0 \
            robotframework-requests==0.7.0

      - name: Run tests
        run: |
          returnCode=0
          SCOPE="ci"
          REPORT_FOLDER="Reports"
          mydir=$PWD
          echo $GITHUB_RUN_ID
          secrets="-v MOBILE_LOGIN:${{ secrets.MOBILE_LOGIN }} -v PASSWORD_LOGIN:${{ secrets.PASSWORD_LOGIN }} -v SLACK_WEBHOOK:${{ secrets.SLACK_WEBHOOK }}"
          options=" -x xUnit -d $REPORT_FOLDER -v Browser:headlesschrome $secrets --norpa --suitestatlevel 2 --xunitskipnoncritical"
          robot $options -v rerun:0 -n skip -o output1.xml Tests/ || returnCode=$?
          echo "------------- $returnCode"
          if [  $returnCode -ne 0  ]; then returnCode=0 && robot $options --runemptysuite -v rerun:1 -e skip -R $REPORT_FOLDER/output1.xml -o output2.xml Tests/ || returnCode=$?; fi
          echo "------------- $returnCode"
          if [  $returnCode -ne 0  ]; then returnCode=0 && robot $options --runemptysuite -v rerun:2 -e skip -R $REPORT_FOLDER/output2.xml -o output3.xml Tests/ || returnCode=$?; fi
          if [  -f $REPORT_FOLDER/output2.xml  ]; then cd $REPORT_FOLDER && rebot --suitestatlevel 2 --ProcessEmptySuite -x xUnit -n skip --xunitskipnoncritical --merge output*.xml || returnCode=$?; fi
          echo "------------- $returnCode"
          cd $mydir && robot -v Build_nbr:$GITHUB_RUN_ID -v JOB_STATUS:$returnCode -d Reports/Notifs -v SCOPE:$SCOPE $secrets --rpa notifications.robot
          exit $returnCode

      - name: Archive test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: Reports/*

